# Generated by Django 3.0.4 on 2020-03-30 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20200330_1059'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
