# Generated by Django 3.0.4 on 2020-05-18 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0002_profile_favorites'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='favorites',
            new_name='favorite',
        ),
    ]
