# Generated by Django 3.0.4 on 2020-05-22 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0004_auto_20200519_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='user_picture/', verbose_name='User Picture'),
        ),
    ]
