# Generated by Django 3.0.4 on 2020-05-22 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0005_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
